### PR TITLE
fix(oauth device): move DeviceCodeEntry out of src/pages (unbreak Next build) + autofocus input

### PR DESCRIPTION
**Pull request by ZacxDev**
## Summary

PR #2647 added `DeviceCodeEntry.tsx` and `DeviceCodeEntry.browser.test.tsx` **under `src/pages/login/oauth/`**. Next.js treats everything under `src/pages/**` as a route and collects it during the build, so a component — and especially a test file — placed there breaks the build. This PR relocates them out of `src/pages/` and fixes the inherited typecheck error, plus autofocuses the code input.

**This unblocks `main`'s Next build (RED since #2647 merged) AND PR #2648's inherited preview failure.** #2648 goes green once this lands on `main` and #2648 is updated (merge `main` into it / rebase). #2648's own e2e test lives under `src/tests/` (which Next ignores) and was never the problem.

## The two failures (from #2648's failed preview pipeline)

1. **build-image (Next build) failed** — Next collected the `.browser.test.tsx` as a page:
   `Type 'typeof import(".../DeviceCodeEntry.browser.test")' does not satisfy the constraint 'PagesPageConfig'`.
2. **typecheck failed** — the browser test called `.rerender` on the render helper's result (a `Promise<RenderResult>`) without awaiting:
   `error TS2339: Property 'rerender' does not exist on type 'Promise<RenderResult>'` (lines 113/126).

## Changes

**A — Relocation (the build fix).** Moved the component + its co-located browser test out of `src/pages/` into `src/components/Login/`, matching the established "browser tests live beside the component under `src/components`" convention (e.g. `src/components/generation_v2/inputs/*.browser.test.tsx`, `src/components/AppBlocks/*.browser.test.tsx`). The repo has **no `pageExtensions`** filter, so relocation IS the fix — Next no longer collects the component/test as pages.

| Old path (`src/pages/`) | New path (`src/components/`) |
|---|---|
| `src/pages/login/oauth/DeviceCodeEntry.tsx` | `src/components/Login/DeviceCodeEntry.tsx` |
| `src/pages/login/oauth/DeviceCodeEntry.browser.test.tsx` | `src/components/Login/DeviceCodeEntry.browser.test.tsx` |

Repointed `device.tsx`'s import to `~/components/Login/DeviceCodeEntry` and fixed the test's relative import depth to `../../../test/component-setup`. `src/server/oauth/user-code.ts` left in place (server, fine). Only the real page route `device.tsx` (+ pre-existing `authorize.tsx`) remains under `src/pages/login/oauth/`.

**B — `.rerender` type fix.** `await` the render helper before `.rerender` (`const { rerender } = await renderWithProviders(...)` + `await rerender(...)`) so the awaited value is a `RenderResult`. No `any` / `@ts-ignore`.

**C — Autofocus.** The code input now focuses on mount (a `ref` + one-shot `useEffect(() => inputRef.current?.focus(), [])`) so the user can paste/type the device code immediately without clicking. The effect runs once and does not re-run on the auto-submit / loading re-renders, so it doesn't fight the existing auto-submit-on-completeness or Enter-to-submit logic. Added a test asserting the input is focused on mount.

## Verification

- **Typecheck**: ran the repo's `tsc --noEmit` against the changed files. The component (`DeviceCodeEntry.tsx`) and the page route (`device.tsx`) typecheck **clean (zero errors)**, and both originally-reported errors are gone (the `.rerender` TS2339 and the `PagesPageConfig` page-collection error). The browser test's remaining `page` / `userEvent` / `expect.element` type complaints under bare `tsc` are pre-existing repo-wide noise identical to every sibling `*.browser.test.tsx` (SeedInput, PageBlockHost, WorkflowInput, …) — they resolve under the vitest browser-mode config at test time, not bare `tsc`; nothing new was introduced.
- **Browser test run**: deferred — the Vitest browser-mode suite (Playwright) doesn't run in this offline environment; logic/types are clean and CI runs the suite.
- **Sanity**: `grep -r "DeviceCodeEntry" src/` shows the page importing from the NEW path with no dangling old-path imports; `src/pages/login/oauth/` contains only `device.tsx` + the pre-existing `authorize.tsx` (no component/test files).

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by CivitaiDevOpsAgent** [comment]
### [PR-REVIEW] round 1 — 0 finding(s) (confidence ≥ 0.80)

No findings at or above the confidence gate this round. ✅

_Automated adversarial review — a triage prior, not approval. Confidence-gated; a human still decides. Posted by `pr-review-svc`._
